---
config:
  layout: elk
  theme: dark
---
flowchart LR

    gcr:s:iam:public_access{"IAM Public"} --> gcr:s:n8n
    subgraph gce:n8n:network VPC
      subgraph gce:n8n:subnet Subnet

        gcr:s:n8n["Cloud Run Service"] --> gsa:n8n:sa([Cloud_Run_SA]);
        gcr:s:n8n --> sql:n8n:db:core[("PostgreSQL Database")]
        gcr:s:n8n --> sql:n8n:db:user("Database User")
        gcr:s:n8n --> gcs:n8n:b:bin[["GCS Bucket"]]


        gcp:n8n:iam:client("Cloud SQL Client Role") --> gsa:n8n:sa

        gsm:iam:secret_accessor("Secret Accessor Role") --> gsa:n8n:sa

        sql:n8n:db:core --> sql:n8n:db:instance[("Cloud SQL Instance")]
        sql:n8n:db:user --> gsm:n8n:db:db_password>"secrets.db_password"]
        sql:n8n:db:user --> sql:n8n:db:instance

        gcs:iam:storage_admin("Storage Admin Role") --> gsa:n8n:sa
        gcs:iam:storage_admin --> gcs:n8n:b:bin

        gcr:s:n8n:::Service
        gsa:n8n:sa:::SA
        gcp:n8n:iam:client:::Role
        gsm:iam:secret_accessor:::Role
        gcs:iam:storage_admin:::Role
        sql:n8n:db:user:::Role
        sql:n8n:db:user:::User
        gcs:n8n:b:bin:::Storage
        gsm:n8n:db:db_password:::Secret
        sql:n8n:db:core:::Storage
        sql:n8n:db:instance:::Storage


        classDef SA stroke-width:2px, color:#A00,stroke:#A00, fill:#FCC
        classDef Role stroke-dasharray: 5 5, fill: #FDC, color:#950, stroke:#950
        classDef Service stroke-width:3px, stroke:#00A, color:#00A, fill:#CCF
        classDef Storage fill:#EFE, color:#0A5, stroke:#0A5
        classDef Secret color:#000, stroke:#FFF, fill:#555
        classDef User stroke-width:3px
        classDef VPC stroke-dasharray: 5 5
        classDef Subnet stroke-dasharray: 5 10
      end
  end
